config/routes.rb
Rails.application.routes.draw do
  root to: "public#homepage" ,as: "home"
  devise_for :accounts

  scope '/charge' do
    post 'create', to: 'charges#create', as: 'charge_create'
    get 'success', to: 'charges#success', as: 'charge_success'
    get 'cancel', to: 'charges#cancel', as: 'charge_cancel'
  end
  resources :items, only: [:index], as: :items
  resources :posts, only: [:new, :create, :show, :destroy]
  resources :comments, only: [:create, :destroy]
  resources :conversations, only: [:create] do
    member do
      post :close
    end
    resources :messages, only: [:create]
  end


  devise_scope :account do
    get '/accounts/sign_out', to: 'devise/sessions#destroy'
    get '/login', to: 'devise/sessions#new'
    get '/registrations' => 'accounts/registrations#new'
  end

  get '/messages' => 'accounts#messages', as: :messages
  get 'usery' => 'accounts#index', as: :usery
  get 'post/like/:post_id' => 'likes#save_like', as: :like_post
  get '/dashboard' => "accounts#dashboard", as: :dashboard
  get 'profile/:username', to: 'accounts#profile', as: :profile
  post 'follow/account' => 'accounts#follow_account', as: :follow_account
  get 'friendlist' => 'accounts#friendlist', as: :friendlist
  get 'subscribers' => 'accounts#subscribers', as: :subscribers
  delete '/deletefriend/:follower_id', :to => 'accounts#delete_friend', as: :destroy_friend

end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :account

  validates_presence_of :comment
  validates_presence_of :account_id
  validates_presence_of :post_id

  validates :comment, presence: true

  attr_accessor :return_to

  after_destroy :decrease_post_comment_counter
  after_create :increase_post_comment_counter

  private

  def increase_post_comment_counter
    Post.find(self.post_id).increment(:total_comments_count).save
  end

  def decrease_post_comment_counter
    Post.find(self.post_id).decrement(:total_comments_count).save
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_account!, :set_account

  def create
    @comment = Comment.new(comment_params)
    @comment.account_id = current_account.id if account_signed_in?
    respond_to do |format|
      if @comment.save
        format.js
      else
        format.html { render :'posts/show' }
      end
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy
    respond_to do |format|
      format.js
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:comment, :post_id, :return_to)
  end

  def set_account
    @current_account = Post.find(params[:account_id]) if params[:account_id].present?
  end
end

app/views/comments/_comment.html.haml
.comment
  -if @comment != nil
    =link_to profile_picture(@comment.account, 45), profile_path(@comment.account.username)
    %strong= link_to @comment.account.username
    -if @current_account != nil
      -if @comment.account.id == @current_account.id
        = link_to comment_path(@comment), method: :delete, class: "btn btn-default btn-xs float-right delete", data:{ remote: true } do
          %i.fa.fa-times
    .content
      =@comment.comment
    %p.text-muted
      =time_ago_in_words @comment.created_at
      ago

app/views/comments/create.js.erb
$("#post-<%=@comment.post_id%>-comments").append("<%= j render 'comments/comment' %>");

app/views/comments/destroy.js.erb
$('.delete').bind('ajax:success', function(){
  $(this).closest('.comment').fadeOut('fast')
})