config/routes.rb
Rails.application.routes.draw do
  root to: "public#homepage" ,as: "home"
  devise_for :accounts

  scope '/charge' do
    post 'create', to: 'charges#create', as: 'charge_create'
    get 'success', to: 'charges#success', as: 'charge_success'
    get 'cancel', to: 'charges#cancel', as: 'charge_cancel'
  end
  resources :items, only: [:index], as: :items
  resources :posts, only: [:new, :create, :show, :destroy]
  resources :comments, only: [:create, :destroy]
  resources :conversations, only: [:create] do
    member do
      post :close
    end
    resources :messages, only: [:create]
  end


  devise_scope :account do
    get '/accounts/sign_out', to: 'devise/sessions#destroy'
    get '/login', to: 'devise/sessions#new'
    get '/registrations' => 'accounts/registrations#new'
  end

  get '/messages' => 'accounts#messages', as: :messages
  get 'usery' => 'accounts#index', as: :usery
  get 'post/like/:post_id' => 'likes#save_like', as: :like_post
  get '/dashboard' => "accounts#dashboard", as: :dashboard
  get 'profile/:username', to: 'accounts#profile', as: :profile
  post 'follow/account' => 'accounts#follow_account', as: :follow_account
  get 'friendlist' => 'accounts#friendlist', as: :friendlist
  get 'subscribers' => 'accounts#subscribers', as: :subscribers
  delete '/deletefriend/:follower_id', :to => 'accounts#delete_friend', as: :destroy_friend

end

app/models/conversation.rb
class Conversation < ApplicationRecord

  has_many :messages, dependent: :destroy
  belongs_to :sender, foreign_key: :sender_id, class_name: Account.to_s
  belongs_to :recipient, foreign_key: :recipient_id, class_name: Account.to_s

  validates :sender_id, uniqueness: { scope: :recipient_id }

  scope :between, -> (sender_id, recipient_id) do
    where(sender_id: sender_id, recipient_id: recipient_id).or(
        where(sender_id: recipient_id, recipient_id: sender_id)
    )
  end

  def self.get(sender_id, recipient_id)
    conversation = between(sender_id, recipient_id).first
    return conversation if conversation.present?

    create(sender_id: sender_id, recipient_id: recipient_id)
  end

  def opposed_account(account)
    account == recipient ? sender : recipient
  end

end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController

  def create
    @conversation = Conversation.get(current_account.id, params[:account_id])

    add_to_conversations unless conversated?

    respond_to do |format|
      format.js
    end
  end

  def close
    @conversation = Conversation.find(params[:id])

    session[:conversations].delete(@conversation.id)

    respond_to do |format|
      format.js
    end
  end

  private

  def add_to_conversations
    session[:conversations] ||= []
    session[:conversations] << @conversation.id
  end

  def conversated?
    session[:conversations].include?(@conversation.id)
  end
end

app/views/conversations/_conversation.html.haml
%li.margin-bottom-20
  .panel.panel-default{"data-conversation-id" => conversation.id}
    .panel-heading
      = link_to conversation.opposed_account(account).username, '', class: 'toggle-window text-dark'
      = link_to "x", close_conversation_path(conversation), class: "btn btn-default btn-xs float-right", remote: true, method: :post
    .panel-body{:style => "display: none;"}
      .messages-list
        %ul= render 'conversations/conversation_content', messages: conversation.messages, account: account
      = form_for [conversation, conversation.messages.new], remote: true do |f|
        = f.hidden_field :account_id, value: account.id
        = f.text_area :body, class: "form-control"
        = f.submit "Send", class: "btn btn-success"

app/views/conversations/_conversation_content.html.haml
- messages.each do |message|
  = render message, account: account

app/views/conversations/close.js.erb
$('#conversations-list').find("[data-conversation-id='" + "<%= @conversation.id %>" + "']").parent().remove();

app/views/conversations/create.js.erb
var conversations = $('#conversations-list');
var conversation = conversations.find("[data-conversation-id='" + "<%= @conversation.id %>" + "']");

if (conversation.length !== 1) {
  conversations.append("<%= j(render 'conversations/conversation', conversation: @conversation, account: current_account) %>");
  conversation = conversations.find("[data-conversation-id='" + "<%= @conversation.id %>" + "']");
}

conversation.find('.panel-body').show();

var messages_list = conversation.find('.messages-list');
var height = messages_list[0].scrollHeight;
messages_list.scrollTop(height);