config/routes.rb
Rails.application.routes.draw do
  root to: "public#homepage" ,as: "home"
  devise_for :accounts

  scope '/charge' do
    post 'create', to: 'charges#create', as: 'charge_create'
    get 'success', to: 'charges#success', as: 'charge_success'
    get 'cancel', to: 'charges#cancel', as: 'charge_cancel'
  end
  resources :items, only: [:index], as: :items
  resources :posts, only: [:new, :create, :show, :destroy]
  resources :comments, only: [:create, :destroy]
  resources :conversations, only: [:create] do
    member do
      post :close
    end
    resources :messages, only: [:create]
  end


  devise_scope :account do
    get '/accounts/sign_out', to: 'devise/sessions#destroy'
    get '/login', to: 'devise/sessions#new'
    get '/registrations' => 'accounts/registrations#new'
  end

  get '/messages' => 'accounts#messages', as: :messages
  get 'usery' => 'accounts#index', as: :usery
  get 'post/like/:post_id' => 'likes#save_like', as: :like_post
  get '/dashboard' => "accounts#dashboard", as: :dashboard
  get 'profile/:username', to: 'accounts#profile', as: :profile
  post 'follow/account' => 'accounts#follow_account', as: :follow_account
  get 'friendlist' => 'accounts#friendlist', as: :friendlist
  get 'subscribers' => 'accounts#subscribers', as: :subscribers
  delete '/deletefriend/:follower_id', :to => 'accounts#delete_friend', as: :destroy_friend

end

app/views/layouts/_account_nav.html.haml
%h5.my-0.mr-md-auto.font-weight-normal= link_to 'First news feed', dashboard_path,  :class => 'btn btn-outline-dark'
%nav.my-2.my-md-0.mr-md-3.mt-md-3
  = form_tag usery_path, :method => 'get'  do
    .input-group.md-form
      = text_field_tag :search, params[:search], :class=> "form-control", :placeholder=>"Search"
      .input-group-append
        = submit_tag :Find do
          %i.fa.fa-envelope
%nav.my-2.my-md-0.mr-md-3= link_to 'Store', items_path, :class => "btn btn-outline-primary"
%nav.my-2.my-md-0.mr-md-3= link_to 'Add post', new_post_path, :class => "btn btn-outline-primary"
%nav.my-2.my-md-0.mr-md-3= link_to 'Friendlist', friendlist_path, :class => "btn btn-outline-primary"
%nav.my-2.my-md-0.mr-md-3= link_to 'Messages', messages_path, :class => "btn btn-outline-primary"
%nav.my-2.my-md-0.mr-md-3= link_to 'Subscribers', subscribers_path, :class => "btn btn-outline-primary"
%nav.my-2.my-md-0.mr-md-3= link_to "My profile", profile_path(current_account.username),  :class => "btn btn-outline-primary"
%nav.my-2.my-md-0.mr-md-3= link_to "Logout", destroy_account_session_path, method: :delete, data: { confirm: "Are you sure?" },  :class => "btn btn-outline-primary"

app/views/layouts/_public_nav.html.haml
%h5.my-0.mr-md-auto.font-weight-normal.text-info JDIgram
%nav.my-2.my-md-0.mr-md-3= link_to "Registration", registrations_path, :class => "btn btn-outline-primary"
%nav.my-2.my-md-0.mr-md-3= link_to "Login", login_path, :class => "btn btn-outline-primary"

app/views/layouts/application.html.haml
%head
  %title JDIgram
  = csrf_meta_tags
  = csp_meta_tag

  = stylesheet_link_tag    'application'
  = stylesheet_link_tag    'https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css'
  = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  = javascript_include_tag 'http://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js'

  %body
    .navbar.d-flex.flex-column.flex-md-row.align-items-center.p-3.px-md-4.mb-3.bg-white.border-bottom.box-shadow
      - if account_signed_in?
        =render "layouts/account_nav"
      -else
        =render "layouts/public_nav"
    .container
      = yield