config/routes.rb
Rails.application.routes.draw do
  root to: "public#homepage" ,as: "home"
  devise_for :accounts

  scope '/charge' do
    post 'create', to: 'charges#create', as: 'charge_create'
    get 'success', to: 'charges#success', as: 'charge_success'
    get 'cancel', to: 'charges#cancel', as: 'charge_cancel'
  end
  resources :items, only: [:index], as: :items
  resources :posts, only: [:new, :create, :show, :destroy]
  resources :comments, only: [:create, :destroy]
  resources :conversations, only: [:create] do
    member do
      post :close
    end
    resources :messages, only: [:create]
  end


  devise_scope :account do
    get '/accounts/sign_out', to: 'devise/sessions#destroy'
    get '/login', to: 'devise/sessions#new'
    get '/registrations' => 'accounts/registrations#new'
  end

  get '/messages' => 'accounts#messages', as: :messages
  get 'usery' => 'accounts#index', as: :usery
  get 'post/like/:post_id' => 'likes#save_like', as: :like_post
  get '/dashboard' => "accounts#dashboard", as: :dashboard
  get 'profile/:username', to: 'accounts#profile', as: :profile
  post 'follow/account' => 'accounts#follow_account', as: :follow_account
  get 'friendlist' => 'accounts#friendlist', as: :friendlist
  get 'subscribers' => 'accounts#subscribers', as: :subscribers
  delete '/deletefriend/:follower_id', :to => 'accounts#delete_friend', as: :destroy_friend

end

app/models/account.rb
class Account < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  mount_uploader :image, ImageUploader

  attr_accessor :login

  has_many :posts
  has_many :likes
  has_many :messages
  has_many :conversations, foreign_key: :sender_id

  validates :username, presence: true, uniqueness: true

  def full_name
    "#{first_name} #{last_name}"
  end

  def total_followers
    Follower.where(follower_id: self.id).count
  end

  def total_following
    Follower.where(following_id: self.id).count
  end

  def self.find_for_authentication(conditions)
    login = conditions.delete(:login)
    where(conditions).where(["username = :value OR email = :value", { :value => login }]).first
  end
end

app/controllers/accounts/confirmations_controller.rb
# frozen_string_literal: true

class Accounts::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/accounts/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Accounts::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/accounts/passwords_controller.rb
# frozen_string_literal: true

class Accounts::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/accounts/registrations_controller.rb
# frozen_string_literal: true

class Accounts::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/accounts/sessions_controller.rb
# frozen_string_literal: true

class Accounts::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

   protected

  # If you have extra params to permit, append them to the sanitizer.
   def configure_sign_in_params
     devise_parameter_sanitizer.permit(:sign_in, keys: [:username])
   end
end

app/controllers/accounts/unlocks_controller.rb
# frozen_string_literal: true

class Accounts::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  before_action :authenticate_account!
  before_action :set_account, only: [:profile]

  def index
    @accounts = Account.where(["username LIKE ?", "%#{params[:search]}%"]).limit(10)
  end

  def messages
      session[:conversations] ||= []

      @accounts = Follower.where(follower_id: current_account.id)
      @conversations = Conversation.includes(:recipient, :messages)
                           .find(session[:conversations])

  end

  def dashboard
    following_ids = Follower.where(follower_id: current_account.id).map(&:following_id)
    following_ids << current_account.id
    @follower_suggestions = Account.where.not(id: following_ids)
    @posts = Post.includes(:account).where(account_id: following_ids).active
    @comment = Comment.new
    @post = Post.find(params[:id]) if params[:id].present?
  end

  def friendlist
    @friends = Follower.where(follower_id: current_account.id)
  end

  def subscribers
    @subscribers = Follower.where(following_id: current_account.id)
  end

  def profile
    @posts = @account.posts.active
  end

  def delete_friend
    @follower = Follower.find(params[:follower_id])
    respond_to do |format|
      format.js
    end
    @follower.destroy
  end

  def follow_account
    follower_id = params[:follow_id]
    @follower = Follower.create(follower_id: current_account.id, following_id: follower_id)
    respond_to do |format|
      format.js
    end
  end

  private

  def set_account
    @account = Account.find_by_username(params[:username])
  end

end

app/helpers/accounts_helper.rb
module AccountsHelper

  def profile_picture account, width = 50
    image_path = account.image.present? ? account.image.url : "default.png"
    image_tag(image_path, width: width, height: width, class: "profile-pic m-r-10")
  end

end

app/views/accounts/_button_add_to_friend.html.haml
=form_tag follow_account_path, method: :post, class: "float-right follow", remote: true do
  = hidden_field_tag :follow_id, friend
  = submit_tag "Follow", class: "btn btn-info btn-sm float-right follow",  remote: true

app/views/accounts/_button_remove_from_friend.html.haml
%i{id: "my-#{couple.following_id}-friend"}
  =link_to 'Delete', destroy_friend_path(couple.id), method: :delete, class: "btn btn-danger btn-sm float-right delete", data: { remote: true}

app/views/accounts/_follower_suggestions.html.haml
-@follower_suggestions.each do |account|
  .recommended-follower
    .row
      .col-sm-3.col-lg-2
        =link_to profile_picture(account, 40), profile_path(account.username)
      .col-sm-9.col-lg-10
        %i{id: "my-#{account.id}-friend"}
          =render "accounts/button_add_to_friend", friend: account.id
        =link_to account.username, profile_path(account.username), :class => "text-dark"
    %p=account.created_at < 1.days.ago ? "New to this Application" : "Followed by X users"

app/views/accounts/dashboard.html.haml
.container
  .row
    .col-6
      -@posts.each do |post|
        .insta-post
          .post-meta
            =link_to profile_picture(post.account), profile_path(post.account.username)
            =link_to post.account.username, profile_path(post.account.username), :class => "text-dark"
          -if  post.image?
            =image_tag post.image.url,  class: "img img-fluid"

          .post-details
            .post-actions
              %i{:class => "fa fa-heart like-#{post.id}#{'active' if post_liked_by_user?(post.id)} fa-2x post-like", "data-id" => post.id}
              =link_to post_path(post.id) do
                %i.fa.fa-comment.fa-2x.post-comment.forcom
            %p
              %strong{:id => "post-#{post.id}-likes"}
                = post.total_likes_count
                likes
            %p
              %strong{:id => "post-#{post.id}-author"}= link_to post.account.username, profile_path(post.account.username), class: "text-dark"
              %p
                =link_to post.account.username, profile_path(post.account.username), :class => "text-dark"
            = simple_format post.description
            %p.text-muted
              = time_ago_in_words post.created_at
              ago
            .comments-feed{id: "post-#{post.id}-comments", "data-id" => post.id }
              = render 'posts/comments', post: post, comments: Comment.includes(:account).where(post_id: post.id)
            .comment-box
              =form_with(model: @comment, remote: true) do |f|
                =f.hidden_field :post_id, value: post.id
                .input-group.mb-3
                  =f.text_field :comment, placeholder: "Add comment here...", class: "form-control post-comment"
                  .input-group-append
                    =f.submit "Post", class: "btn btn-secondary float-right", remote: true
    .col-4
      .account-summary
        %p.m-0.class-padding-15
          =link_to image_tag(current_account.image.thumb.url,width: "50px", height: "50px", class: "profile-pic float-left m-r-15"), profile_path(current_account.username) if current_account.image.present?
          %strong=link_to current_account.username, profile_path(current_account.username)
          %br
            =current_account.full_name
        .follower-suggestions
          %p.text-muted Suggestion for you
          =render "accounts/follower_suggestions"

app/views/accounts/delete_friend.js.erb
$('.delete').bind('ajax:success', function(){
  $(this).closest('.delete').fadeOut('fast')
});

$("#my-<%= @follower.following_id %>-friend").append("<%= j render 'accounts/button_add_to_friend', friend: @follower.following_id %>")

app/views/accounts/follow_account.js.erb
$(".follow").bind('ajax:success', function(){
  $(this).closest(".follow").fadeOut('fast')
});

$("#my-<%= @follower.following_id %>-friend").append("<%= j render 'accounts/button_remove_from_friend', couple: @follower %>")

app/views/accounts/friendlist.html.haml
-@friends.each do |friend|
  -i = Account.find(friend.following_id)
  .account-summary
    %i
      =link_to profile_picture(i, 70), profile_path(i.username)
      =link_to i.username, profile_path(i.username), :class => "text-dark"
      %i{id: "my-#{i.id}-friend"}
        =link_to 'Delete', destroy_friend_path(friend), method: :delete, class: "btn btn-danger btn-sm float-right delete", data: { remote: true}

app/views/accounts/index.html.haml
-@accounts.each do |account|
  .account-summary
    -if account.username != current_account.username
      - this_friend = Follower.find_by(following_id: account.id, follower_id: current_account.id)
      =link_to profile_picture(account, 70), profile_path(account.username)
      =link_to account.username, profile_path(account.username), :class => "text-dark"
      -if this_friend
        %i{id: "my-#{this_friend.following_id}-friend"}
          = link_to 'Delete', destroy_friend_path(this_friend), method: :delete, class: "btn btn-danger btn-sm float-right delete", data: { remote: true}
      -else
        %i{id: "my-#{account.id}-friend"}
          = render "accounts/button_add_to_friend", friend: account.id

app/views/accounts/messages.html.haml
.row
  .col-md-9
    %ul#conversations-list
      - @conversations.each do |conversation|
        -if conversation.opposed_account(@account).username != current_account.username
          = render 'conversations/conversation', conversation: conversation, account: current_account
  .col-md-3
    .panel.panel-primary
      .panel-heading
        %h3.panel-title User list
      .panel-body
        %ul
          -@accounts.each do |friend|
            -i = Account.find(friend.following_id)
            %li= link_to i.username, conversations_path(account_id: i), remote: true, method: :post

app/views/accounts/profile.html.haml
.container
  .row
    .col-4
      =profile_picture @account, 200
    .col-8.text-left
      .row
        .col-6
          %h1
            -if current_account.username == @account.username
              = link_to 'Edit profile', edit_account_registration_path, :class => "btn btn-outline-info float-right"
            -else
              -this_friend = Follower.find_by(following_id: @account.id, follower_id: current_account.id)
              -if this_friend
                %i{id: "my-#{this_friend.following_id}-friend"}
                  = link_to 'Delete', destroy_friend_path(this_friend), method: :delete, class: "btn btn-danger btn-sm float-right delete", data: { remote: true}
              -else
                %i{id: "my-#{@account.id}-friend"}
                  = render "accounts/button_add_to_friend", friend: @account.id

            = @account.full_name

      .row.profile-stats
        .col-4
          =@account.posts.count
          posts
        .col-4
          ="#{@account.total_followers} followers"
        .col-4
          =@account.total_following
          following

      %p=@account.full_name
      =simple_format @account.description
      %p=link_to @account.website if @account.website.present?
  .row.profile-post
    -@posts.each do |post|
      .col-4
        .insta-post.post-square{:style=> "background: url(#{post.image.url}) no-repeat center top" }
          =link_to post_path(post) do
            .post-stats
              .inner
                %i.fa.fa-heart= post.total_likes_count
                %i.fa.fa-comment.m-l-15= post.total_comments_count
            %br

app/views/accounts/subscribers.html.haml
-@subscribers.each do |friend|
  -i = Account.find(friend.follower_id)
  .account-summary
    %p.m-0.class-padding-15
      =link_to profile_picture(i, 70), profile_path(i.username)
      =link_to i.username, profile_path(i.username), :class => "text-dark"